### ISSUE TITLE
Organize and separate list based on language stack or the functionality

### ISSUE THREAD

**Issue by techgaun** [dev-nepal/awesome-nepal#2]
How should we organize the list of the awesome stuffs? Or, its not necessary to organize at the moment and we can refactor later?
cc: @dev-nepal/contributors

**Comment by ankitpokhrel** [comment]
I would prefer to organize the list from first. Atleast using basic methods like projects based on language used (any other ideas?) and when the list grows bigger we can find out new way of organizing the list.

**Comment by techgaun** [comment]
@ankitpokhrel sounds good. Lets hear few other opinions from the community and we can decide for later.

**Comment by ankitpokhrel** [comment]
@techgaun Should we add author name like I added for prepros or is it not necessary?

**Comment by techgaun** [comment]
@ankitpokhrel I personally think if we link to the github project, it is probably redundant to specify. What's your opinion?

**Comment by ankitpokhrel** [comment]
@techgaun that would be fine!
